export declare enum AfriexErrorCode {
    INVALID_API_KEY = "INVALID_API_KEY",
    UNAUTHORIZED = "UNAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
    INVALID_REQUEST = "INVALID_REQUEST",
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",
    INVALID_FIELD_FORMAT = "INVALID_FIELD_FORMAT",
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
    TRANSFER_LIMIT_EXCEEDED = "TRANSFER_LIMIT_EXCEEDED",
    INVALID_RECIPIENT = "INVALID_RECIPIENT",
    UNSUPPORTED_CURRENCY = "UNSUPPORTED_CURRENCY",
    UNSUPPORTED_COUNTRY = "UNSUPPORTED_COUNTRY",
    TRANSACTION_FAILED = "TRANSACTION_FAILED",
    TRANSACTION_PENDING = "TRANSACTION_PENDING",
    TRANSACTION_DECLINED = "TRANSACTION_DECLINED",
    NETWORK_ERROR = "NETWORK_ERROR",
    TIMEOUT = "TIMEOUT",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
}
export declare const ERROR_CODE_MESSAGES: Record<AfriexErrorCode, string>;
//# sourceMappingURL=ErrorCodes.d.ts.map